"""Initial tables

Revision ID: e511063f1166
Revises: 
Create Date: 2026-09-03 16:21:53.143701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e511063f1166'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_username_email', 'users', ['username', 'email'], unique=False)
    op.create_table('dashboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_author_id'), 'dashboards', ['author_id'], unique=False)
    op.create_table('columns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('backlog', 'ready', 'in_progress', 'in_viewer', 'done', 'overdue', name='status_enum'), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_columns_dashboard_id'), 'columns', ['dashboard_id'], unique=False)
    op.create_table('viewers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'dashboard_id')
    )
    op.create_index('idx_viewer_dashboard_id', 'viewers', ['dashboard_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='priority_enum'), nullable=False),
    sa.Column('time_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('column_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_column_position', 'tasks', ['column_id', 'position'], unique=False)
    op.create_index(op.f('ix_tasks_author_id'), 'tasks', ['author_id'], unique=False)
    op.create_table('assignees',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'task_id')
    )
    op.create_index('idx_assignee_task_id', 'assignees', ['task_id'], unique=False)
    op.create_table('tasks_tags',
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'task_id')
    )
    op.create_index('idx_task_tag_task_id', 'tasks_tags', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_tag_task_id', table_name='tasks_tags')
    op.drop_table('tasks_tags')
    op.drop_index('idx_assignee_task_id', table_name='assignees')
    op.drop_table('assignees')
    op.drop_index(op.f('ix_tasks_author_id'), table_name='tasks')
    op.drop_index('idx_column_position', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_viewer_dashboard_id', table_name='viewers')
    op.drop_table('viewers')
    op.drop_index(op.f('ix_columns_dashboard_id'), table_name='columns')
    op.drop_table('columns')
    op.drop_index(op.f('ix_dashboards_author_id'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index('idx_username_email', table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
